### ISSUE TITLE
Авторизация пользователей

### ISSUE THREAD

**Issue by Heardline** [Heardline/Dwellers_app#13]
- [x] #12 Сделать генерацию одноразовых кодов
- [ ] #12 Проверку в боте и сайте
- [ ] #12 Прописать методы регистрации пользователя и проверки
- [ ] #11 Сверстать страницу регистрации и входа

**Comment by Heardline** [comment]
![alt Прототип](https://github.com/Heardline/Dwellers_app/blob/main/UI_prototype_login.png)
