### ISSUE TITLE
Оплата счетов (личный кабинет)

### ISSUE THREAD

**Issue by Heardline** [Heardline/Dwellers_app#14]
- [ ] #12 Реализовать модуль payments
- [ ] #12 Сделать модель счетов
- [ ] Продумать варианты выставления счетов
- [ ] #12 Прописать основную логику
- [ ] Определиться с сервисом оплаты
