### ISSUE TITLE
Колл-центр. Обратная связь

### ISSUE THREAD

**Issue by Heardline** [Heardline/Dwellers_app#5]
- [ ] #12 Создать модуль FeedBack
- [ ] #12 Создать API метод 
- [ ] #11 Сверстать страницу обратной связи
