### ISSUE TITLE
Создание пропусков для машины

### ISSUE THREAD

**Issue by Heardline** [Heardline/Dwellers_app#6]
- [ ] #12 Создать модель пропусков для машин
- [ ] #12 Создать форму
- [ ] #12 Сделать API метод создания пропуска
- [ ] #2 Сделать варианты генерации пропуска через TelegramBot
